### ISSUE TITLE
compatible with?

### ISSUE THREAD

**Issue by Brujodedor** [baugarten/node-restful#58] opened 2014-03-30 23:29 UTC
is only compatible with mongodb or work with another like couchdb, hadoop or something?

is compatible with an orms like postgresql, mysql, oracle, sqlserver or something?

thanks

**Comment by OmgImAlexis** [comment] 2017-01-29 05:35
This can be closed as it's a duplicate of https://github.com/baugarten/node-restful/issues/50.

**Closed** 2017-02-13 19:04 UTC
